services:
  ingestion:
    build:
      context: .
      network: host
    container_name: gep-ingestion
    env_file:
      - .env
    environment:
      - BRONZE_ROOT=${BRONZE_ROOT}
      - CSV_INPUT_DIR=${CSV_INPUT_DIR}
      - API_BASE_URL=${API_BASE_URL}
      - DB_JDBC_URL=${DB_JDBC_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - SILVER_PATH=${SILVER_PATH}
    volumes:
      - bronze_data:/data/bronze
      - ~/projects/global-energy-platform/fake_data_platform/output/csv:/data/raw/csv
    networks:
      - fake_data_platform_energy_network
    restart: "no"

volumes:
  bronze_data:
  csv_raw:

networks:
  fake_data_platform_energy_network:
    external: true